In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df.head()

bodyTemp  bodyPain  runnyNose  diffBreath  o2Saturation  travelHistory  \
0  101.441399         1          0          -1            89              1   
1  100.982812         0          0          -1            95              0   
2  101.185510         0          1          -1            92              0   
3   99.841183         1          1           1            78              1   
4   99.167192         0          0           1            76              1   

   age  LossofTasteSmell  vomiting  Diarrhea  infectionProb  
0   36                 0         0         0              1  
1   33                 0         0         0              0  
2   96                 1         0         0              0  
3   65                 1         0         1              1  
4   84                 0         1         0              1

In [4]:
df.tail()

bodyTemp  bodyPain  runnyNose  diffBreath  o2Saturation  \
2494   99.947438         0          1           1            95   
2495   98.350472         0          0           0            92   
2496  100.196342         0          1           1            92   
2497   98.933927         0          0          -1            88   
2498  100.194224         1          0           0            61   

      travelHistory  age  LossofTasteSmell  vomiting  Diarrhea  infectionProb  
2494              0   17                 1         1         1              0  
2495              0   84                 0         0         0              0  
2496              0   72                 1         1         0              0  
2497              1   98                 0         0         1              1  
2498              1    8                 0         0         1              1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2499 entries, 0 to 2498
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   bodyTemp          2499 non-null   float64
 1   bodyPain          2499 non-null   int64  
 2   runnyNose         2499 non-null   int64  
 3   diffBreath        2499 non-null   int64  
 4   o2Saturation      2499 non-null   int64  
 5   travelHistory     2499 non-null   int64  
 6   age               2499 non-null   int64  
 7   LossofTasteSmell  2499 non-null   int64  
 8   vomiting          2499 non-null   int64  
 9   Diarrhea          2499 non-null   int64  
 10  infectionProb     2499 non-null   int64  
dtypes: float64(1), int64(10)
memory usage: 214.9 KB


In [6]:
df['bodyTemp'].value_counts()

101.441399    99
100.982812    97
99.841183     66
101.137272    64
99.167192     64
              ..
100.753163     1
101.140293     1
101.790601     1
98.732287      1
99.832280      1
Name: bodyTemp, Length: 532, dtype: int64

In [7]:
df.describe()

bodyTemp     bodyPain    runnyNose   diffBreath  o2Saturation  \
count  2499.000000  2499.000000  2499.000000  2499.000000   2499.000000   
mean    100.138546     0.422569     0.601841    -0.010804     78.124050   
std       1.096522     0.494067     0.489617     0.848091     15.053887   
min      98.015804     0.000000     0.000000    -1.000000     50.000000   
25%      99.179472     0.000000     0.000000    -1.000000     66.000000   
50%     100.196342     0.000000     1.000000     0.000000     83.000000   
75%     101.137272     1.000000     1.000000     1.000000     92.000000   
max     101.998962     1.000000     1.000000     1.000000     95.000000   

       travelHistory          age  LossofTasteSmell   vomiting     Diarrhea  \
count    2499.000000  2499.000000       2499.000000  2499.0000  2499.000000   
mean        0.519008    46.514206          0.259704     0.5002     0.455782   
std         0.499739    26.990734          0.438560     0.5001     0.498141   
min         0.000000     1.000000          0.000000     0.0000     0.000000   
25%         0.000000    25.000000          0.000000     0.0000     0.000000   
50%         1.000000    42.000000          0.000000     1.0000     0.000000   
75%         1.000000    67.000000          1.000000     1.0000     1.000000   
max         1.000000   100.000000          1.000000     1.0000     1.000000   

       infectionProb  
count    2499.000000  
mean        0.536214  
std         0.498787  
min         0.000000  
25%         0.000000  
50%         1.000000  
75%         1.000000  
max         1.000000

## Spliting the data


In [8]:
import numpy as np

In [9]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled=np.random.permutation(len(data))
    test_set_size= int(len(data)*ratio)
    test_indices= shuffled[:test_set_size]
    train_indices= shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [10]:
train,test=data_split(df,0.2)

In [11]:
train

bodyTemp  bodyPain  runnyNose  diffBreath  o2Saturation  \
461    99.825482         0          1          -1            92   
109    99.573732         0          1          -1            66   
2296   99.831461         1          0           0            75   
354   101.152159         0          1           0            92   
266   100.691629         1          0           1            90   
...          ...       ...        ...         ...           ...   
1638   98.216911         1          0           1            70   
1095  101.051166         0          1           1            67   
1130  100.308015         0          0          -1            95   
1294  100.982812         0          0          -1            95   
860   101.933292         0          0           1            85   

      travelHistory  age  LossofTasteSmell  vomiting  Diarrhea  infectionProb  
461               0   19                 0         1         0              0  
109               0   48                 0         0         0              0  
2296              1    5                 0         1         1              0  
354               0   25                 0         1         0              0  
266               1   75                 1         1         1              1  
...             ...  ...               ...       ...       ...            ...  
1638              1   62                 0         1         0              1  
1095              0   14                 0         1         1              1  
1130              1   32                 0         1         0              0  
1294              0   33                 0         0         0              0  
860               0   70                 1         1         1              0  

[2000 rows x 11 columns]

In [12]:
test


bodyTemp  bodyPain  runnyNose  diffBreath  o2Saturation  \
2319   98.357745         0          1           0            95   
1865  100.601893         1          1           1            88   
902   101.501663         0          0          -1            50   
2240  100.763833         1          0          -1            52   
1285  101.051166         0          1           1            67   
...          ...       ...        ...         ...           ...   
1037   98.933927         0          0          -1            88   
2054  101.548704         0          1           1            65   
1860  101.493547         1          1           0            73   
1862   98.482715         0          1           1            52   
1151   99.501306         0          1          -1            95   

      travelHistory  age  LossofTasteSmell  vomiting  Diarrhea  infectionProb  
2319              1    8                 0         0         1              0  
1865              0   97                 0         0         1              1  
902               0   25                 0         0         0              0  
2240              0   59                 0         1         1              1  
1285              0   14                 0         1         1              1  
...             ...  ...               ...       ...       ...            ...  
1037              1   98                 0         0         1              1  
2054              1   61                 0         1         0              1  
1860              1   32                 1         0         0              1  
1862              0   44                 0         1         1              0  
1151              0   37                 0         0         1              0  

[499 rows x 11 columns]

## convert in to numpy array

In [13]:
x_train=train[['bodyTemp','bodyPain','runnyNose','diffBreath','o2Saturation','travelHistory','age','LossofTasteSmell','vomiting','Diarrhea']]

In [14]:
x_train.to_numpy()

array([[ 99.8254821 ,   0.        ,   1.        , ...,   0.        ,
          1.        ,   0.        ],
       [ 99.5737325 ,   0.        ,   1.        , ...,   0.        ,
          0.        ,   0.        ],
       [ 99.83146071,   1.        ,   0.        , ...,   0.        ,
          1.        ,   1.        ],
       ...,
       [100.3080155 ,   0.        ,   0.        , ...,   0.        ,
          1.        ,   0.        ],
       [100.982812  ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [101.9332921 ,   0.        ,   0.        , ...,   1.        ,
          1.        ,   1.        ]])

In [15]:
x_train=train[['bodyTemp','bodyPain','runnyNose','diffBreath','o2Saturation','travelHistory','age','LossofTasteSmell','vomiting','Diarrhea']].to_numpy()

In [16]:
x_test=test[['bodyTemp','bodyPain','runnyNose','diffBreath','o2Saturation','travelHistory','age','LossofTasteSmell','vomiting','Diarrhea']].to_numpy()

In [27]:
y_train=train[['infectionProb']].to_numpy()

In [28]:
y_train

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [18]:
y_test=test[['infectionProb']].to_numpy()

## Reshape the data


In [19]:
y_train=train[['infectionProb']].to_numpy().reshape(2000,)
y_test=test[['infectionProb']].to_numpy().reshape(499,)

## LogisticRegression

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
clf=LogisticRegression()

In [22]:
clf.fit(x_train,y_train)

LogisticRegression()

In [23]:
clf.predict([[99.82,1,0,-1,89,1,36,0,1,0]])

array([1], dtype=int64)

In [24]:
clf.predict_proba([[99.82,1,0,-1,89,1,36,0,1,0]])

array([[0.47224271, 0.52775729]])

In [25]:
inputFeatures= ([[99.82,1,0,1,89,1,50,0,1,1]])


In [26]:
clf.predict_proba(inputFeatures)

array([[0.10794617, 0.89205383]])